# Generated by Django 6.0 on 2025-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0005_schoolclass_description_schoolclass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
