# Generated by Django 6.0 on 2025-12-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0007_feestructure_feecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='feecollection',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='FeeCollection',
        ),
    ]
