# Generated by Django 6.0 on 2026-01-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0021_hostel_hostelfee_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='school_class',
        ),
        migrations.DeleteModel(
            name='FeeBill',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
