# Generated by Django 6.0 on 2026-01-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0023_feebill_feepayment_feestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='student_barcodes/'),
        ),
    ]
