# Generated by Django 6.0 on 2026-01-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0024_student_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfee',
            name='hostel',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='HostelFee',
        ),
    ]
