# Generated by Django 6.0 on 2026-01-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0026_hostel_hostelfee_room_roomallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys Hostel'), ('Girls', 'Girls Hostel')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
