# Generated by Django 6.0 on 2026-01-09 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0027_hostel_hostel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportallocation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
