# Generated by Django 6.0 on 2026-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0028_alter_transportallocation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportallocation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
