# Generated by Django 6.0 on 2026-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0029_alter_transportallocation_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportallocation',
            name='start_date',
        ),
    ]
