# Generated by Django 6.0 on 2026-01-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0030_remove_transportallocation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfee',
            name='hostel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schoolsoftware_app.hostel'),
            preserve_default=False,
        ),
    ]
