# Generated by Django 6.0 on 2026-01-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0031_hostelfee_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelfee',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolsoftware_app.hostel'),
        ),
    ]
