# Generated by Django 6.0 on 2026-01-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0032_alter_hostelfee_hostel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelFee',
        ),
    ]
