# Generated by Django 6.0 on 2026-01-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0034_hostelfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelFee',
        ),
    ]
