# Generated by Django 6.0 on 2026-01-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0035_delete_hostelfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolsoftware_app.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolsoftware_app.student')),
            ],
        ),
    ]
