# Generated by Django 6.0 on 2026-01-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0036_hostelfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeBillMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='schoolsoftware_app.feebill')),
            ],
        ),
    ]
