# Generated by Django 6.0 on 2026-01-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0038_feebill_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='fine_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
