# Generated by Django 6.0 on 2026-01-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsoftware_app', '0039_bookissue_due_date_bookissue_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpayroll',
            name='payable_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
